export const RESTURANT_LIST = [
  {
    id: 0,
    name: "Chai Code Cafe",
    image: "https://chaicode.com/assets/white-1-CYshgcRl.webp",
    rating: 4.8,
    menu: [],
  },
  {
    id: 1,
    name: "Pizza Hut",
    image: "https://www.pizzahut.com/assets/welcome/images/pizza-hut-logo.png",
    rating: 4.5,
    menu: [],
  },
  {
    id: 2,
    name: "McDonald's",
    image: "https://www.mcdonalds.com/content/dam/usa/nfl/mcd-logo.png",
    rating: 4.0,
    menu: [],
  },
  {
    id: 3,
    name: "KFC",
    image: "https://www.kfc.com/static/images/kfc-logo.png",
    rating: 4.2,
    menu: [],
  },
  {
    id: 4,
    name: "Subway",
    image: "https://www.subway.com/sites/default/files/2020-11/subway-logo.png",
    rating: 4.3,
    menu: [],
  },
  {
    id: 5,
    name: "Burger King",
    image: "https://www.burgerking.com/assets/images/bk-logo.png",
    rating: 4.1,
    menu: [],
  },
  {
    id: 6,
    name: "Taco Bell",
    image: "https://www.tacobell.com/assets/images/taco-bell-logo.png",
    rating: 4.0,
    menu: [],
  },
  {
    id: 7,
    name: "Domino's Pizza",
    image: "https://www.dominos.com/assets/images/dominos-logo.png",
    rating: 4.4,
    menu: [],
  },
  {
    id: 8,
    name: "Starbucks",
    image: "https://www.starbucks.com/assets/images/starbucks-logo.png",
    rating: 4.6,
    menu: [],
  },
  {
    id: 9,
    name: "Dunkin' Donuts",
    image: "https://www.dunkindonuts.com/assets/images/dunkin-logo.png",
    rating: 4.3,
    menu: [],
  },
  {
    id: 10,
    name: "Panda Express",
    image: "https://www.pandaexpress.com/assets/images/panda-express-logo.png",
    rating: 4.2,
    menu: [],
  },
  {
    id: 11,
    name: "Chipotle Mexican Grill",
    image: "https://www.chipotle.com/assets/images/chipotle-logo.png",
    rating: 4.5,
    menu: [],
  },
  {
    id: 12,
    name: "Olive Garden",
    image: "https://www.olivegarden.com/assets/images/olive-garden-logo.png",
    rating: 4.4,
    menu: [],
  },
  {
    id: 13,
    name: "7th Heaven",
    image: "https://www.7thheaven.com/assets/images/7th-heaven-logo.png",
    rating: 4.7,
    menu: [],
  },
  {
    id: 14,
    name: "Foodizen",
    image: "https://www.foodizen.com/assets/images/foodizen-logo.png",
    rating: 4.9,
    menu: [],
  },
];

export const MENU_CATEGORIES = [
  {
    id: 0,
    name: "Pizza",
    image: "https://www.pizzahut.com/assets/welcome/images/pizza-hut-logo.png",
  },
  {
    id: 1,
    name: "Burgers",
    image: "https://www.burgerking.com/assets/images/bk-logo.png",
  },
  {
    id: 2,
    name: "Sushi",
    image: "https://www.sushiexpress.com/assets/images/sushi-express-logo.png",
  },
  {
    id: 3,
    name: "Desserts",
    image:
      "https://www.dessertheaven.com/assets/images/dessert-heaven-logo.png",
  },
  {
    id: 4,
    name: "Drinks",
    image: "https://www.drinkdelight.com/assets/images/drink-delight-logo.png",
  },
];
